### ISSUE TITLE
CountDown SetTotalTime

### ISSUE THREAD

**Issue by LTFENG** [xenione/Digit#10]
Hi dear Author Xenione, 

May I ask is that possible to make it customized that I can called the function like setTotalTime in other fragment ?

I tried to modify the example countdown view, but failed XD because it only limits to 10 hours, and I don't know the best way to modify it.

Hope you can help me.

Thanks Great Work !

**Comment by xenione** [comment]
Hi LTFENG
You can add many tab-digit as you need.

**Comment by LTFENG** [comment]
Thanks for reply me

I am not sure would you read this reply

yes, I know I can add many of tab-digit
btw, I would like to ask where should I modify the countdown view 
in order to make it like fit to any totalhours ?
so I can make a function like setTotalHour in any framework

sorry, if my question is unclear, because the example only fit to 10 hours.

Thanks Xenione

**Comment by LTFENG** [comment]
Thanks for reply me

I am not sure would you read this reply

yes, I know I can add many of tab-digit
btw, I would like to ask for the countdown view
https://github.com/xenione/tab-digit/blob/master/app/src/main/java/com/xenione/demos/digit/CountdownView.java

is it ok to make it fit to any totalhours ?
so I can make a function like setTotalHour in any fragments or activity.

sorry, if my question is unclear, because the example only fit to 10 hours.

Thanks Xenione

**Comment by LTFENG** [comment]
Thanks for reply me

I am not sure would you read this reply

yes, I know I can add many of tab-digit
btw, I would like to ask for the countdown view
https://github.com/xenione/tab-digit/blob/master/app/src/main/java/com/xenione/demos/digit/CountdownView.java

is it ok to make it fit to any totalhours ?
so I can make a function like setTotalHour in any fragments or activity.

sorry, if my question is unclear, because the example only fit to 10 hours.

Thanks @xenione

**Comment by xenione** [comment]
Yes , you can do it. Please take a minute to understand how countdown demo works and I pretty sure you will make it yourself.

**Comment by LTFENG** [comment]
@xenione 
Thanks for your reply =)

` 
// example we take 30 mins (30 * 60) 
totalTime = 30 * 60

val hourHeight = (time / 36000).toInt()
 println("total hour ${time}") // total hour 0
 println("hour height ${hourHeight}") // hour height 0
 println("result ${9-hourHeight}") // result 9
 println("Deximal result - ${DECIMAL[9-hourHeight]}") // Deximal result - 0 ! should this result show in count down ?
 mCharHighHour!!.setChar(9-hourHeight) 
// MAY I ASK why the result show 9 but not 0 ?
`

Thank you once again for reply me. Appreciated

**Comment by LTFENG** [comment]
@xenione 
Thanks for your reply =)

`// example we take 30 mins (30 * 60)
totalTime = 30 * 60

val hourHeight = (time / 36000).toInt()
println("total hour ${time}") // total hour 0
println("hour height ${hourHeight}") // hour height 0
println("result ${9-hourHeight}") // result 9
println("Deximal result - ${DECIMAL[9-hourHeight]}") // Deximal result - 0 ! should this result show in count down ?
mCharHighHour!!.setChar(9-hourHeight)
// MAY I ASK why the result show 9 but not 0 ?`

Thank you once again for reply me. Appreciated

**Comment by LTFENG** [comment]
@xenione
Thanks for your reply =)

```
// example we take 30 mins (30 * 60)
totalTime = 30 * 60

val hourHeight = (time / 36000).toInt()
println("total hour ${time}") // total hour 0
println("hour height ${hourHeight}") // hour height 0
println("result ${9-hourHeight}") // result 9
println("Deximal result - ${DECIMAL[9-hourHeight]}") // Deximal result - 0 ! should this result show in count down ?
mCharHighHour!!.setChar(9-hourHeight)
// MAY I ASK why the result show 9 but not 0 ?
```

Thank you once again for reply me. Appreciated
