### ISSUE TITLE
AAPT: error: duplicate value for resource 'attr/cornerSize' with config ''.

### ISSUE THREAD

**Issue by Mohekkus** [xenione/Digit#14]
on Android Studio 4.0
Build Failed : AAPT: error: duplicate value for resource 'attr/cornerSize' with config ''.
File : jetified-tab-digit-1.0.2/res/values/values.xml Line 3

**Comment by shadowalker77** [comment]
Same error here

**Comment by pamobo0609** [comment]
Are you guys using `implementation "com.google.android.material:material:$materialVersion"`? This error started happening when I updated to it's latest version (`1.1.0`).

**Comment by YogeshRewan1** [comment]
Solved this issue 
(In digit lib)
just open values>attrs file and just change the name of all the item 
and use the same name in clock.xml file
for example
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="TabDigit">
        <attr name="textSizenew" format="dimension" />
        <attr name="paddingnew" format="dimension" />
        <attr name="cornerSizenew" format="dimension" />
        <attr name="textColornew" format="color" />
        <attr name="backgroundColornew" format="color" />
        <attr name="reverseRotationnew" format="boolean" />
    </declare-styleable>
</resources>

**Comment by xenione** [comment]
I think don t need to  change attr name. It should be solve just add namespace to attr, but I m not sure.
