### ISSUE TITLE
About CountDown Mechanism

### ISSUE THREAD

**Issue by kp2912** [xenione/Digit#3]
Hi,
I have to show count down timer from specific date. 
Like, I have event date of 5 months from now and i have to show count down timer using your lib.
Do u have any idea how can we do that in current code?

**Comment by xenione** [comment]
you can make pull request with count down feature, otherwise I m not sure if you setChars() in inverse order like new tabDigit.setChars(new char[]{'9','8','7','6',........}) may work. have a try and tell me if you have any dubt.

**Comment by LTFENG** [comment]
Dear Xenione,

thanks for your great work.

I had tried your method to implement the inverse count down
setChars is worked

but, I would like to know, how can i make it like count down from specific 5 mins or 1 hours like that
may you share me the correct way ?

Thanks
