### ISSUE TITLE
Countdown timer?

### ISSUE THREAD

**Issue by neelkadia-zz** [xenione/Digit#4]
Is there any kind of method so that people can use it as a countdown timer?

**Comment by xenione** [comment]
Nop, but it's not hard to adapt. hint: setChars(new char[]{'9','8'.....}) (invers order) don't forget that when setChar is by position so now 0 is 9 and so on...  . Probably I will do later this month.

**Comment by xenione** [comment]
count down demo added

**Comment by ehsanwwe** [comment]
countdown demo show countup for me
